# Generated by Django 6.1.1 on 2026-09-13 15:59

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('BIRTH', 'Birth'), ('MARRIAGE', 'Marriage'), ('DEATH', 'Death'), ('EDUCATION', 'Education / Graduation'), ('MIGRATION', 'Migration / Relocation'), ('CAREER', 'Career / Business'), ('RESIDENCE', 'Residence'), ('MILITARY', 'Military Service'), ('OTHER', 'Other Milestone')], db_index=True, default='OTHER', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_text', models.CharField(blank=True, help_text="Textual representation like 'Spring 1968'", max_length=100)),
                ('place', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
