# Generated by Django 6.1.1 on 2026-09-13 15:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('birth_year_approx', models.CharField(blank=True, help_text="e.g. 'circa 1920', '1940s', or approx year", max_length=50)),
                ('birth_place', models.CharField(blank=True, max_length=255)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('death_year_approx', models.CharField(blank=True, max_length=50)),
                ('death_place', models.CharField(blank=True, max_length=255)),
                ('is_living', models.BooleanField(db_index=True, default=True)),
                ('biography', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('privacy', models.CharField(choices=[('PUBLIC', 'Public'), ('FAMILY_ONLY', 'Family Only'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='families.family')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
                'ordering': ['birth_date', 'first_name'],
                'indexes': [models.Index(fields=['family', 'last_name', 'first_name'], name='members_per_family__11ef39_idx'), models.Index(fields=['family', 'is_living'], name='members_per_family__7d0711_idx')],
            },
        ),
    ]
