# Generated by Django 6.1.1 on 2026-09-13 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymembership',
            name='status',
            field=models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending Approval'), ('REJECTED', 'Rejected')], db_index=True, default='APPROVED', max_length=20),
        ),
    ]
