# Generated by Django 6.1.1 on 2026-09-13 15:59

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarriagePartnership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('partnership_type', models.CharField(choices=[('MARRIAGE', 'Marriage'), ('CIVIL_UNION', 'Civil Union'), ('DOMESTIC_PARTNERSHIP', 'Domestic Partnership')], default='MARRIAGE', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('start_place', models.CharField(blank=True, max_length=255)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_reason', models.CharField(choices=[('ONGOING', 'Ongoing'), ('DEATH', 'Death of Spouse'), ('DIVORCE', 'Divorce'), ('ANNULMENT', 'Annulment'), ('SEPARATION', 'Separation')], default='ONGOING', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages', to='families.family')),
                ('partner_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_p1', to='members.person')),
                ('partner_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marriages_as_p2', to='members.person')),
            ],
            options={
                'verbose_name': 'Marriage / Partnership',
                'verbose_name_plural': 'Marriages & Partnerships',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('PARENT_CHILD', 'Parent - Child'), ('SPOUSE', 'Spouse'), ('PARTNER', 'Partner'), ('SIBLING', 'Sibling'), ('GUARDIAN', 'Guardian - Ward')], db_index=True, max_length=30)),
                ('relationship_subtype', models.CharField(choices=[('BIOLOGICAL', 'Biological'), ('ADOPTIVE', 'Adoptive'), ('STEP', 'Step'), ('FOSTER', 'Foster'), ('UNKNOWN', 'Unknown')], default='BIOLOGICAL', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='families.family')),
                ('person_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_subject', to='members.person')),
                ('person_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_as_target', to='members.person')),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
                'indexes': [models.Index(fields=['family', 'person_a', 'relationship_type'], name='relationshi_family__f36fa2_idx'), models.Index(fields=['family', 'person_b', 'relationship_type'], name='relationshi_family__51cb59_idx')],
                'unique_together': {('family', 'person_a', 'person_b', 'relationship_type', 'relationship_subtype')},
            },
        ),
    ]
