# Generated by Django 6.1.1 on 2026-09-13 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('families', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='family_media/')),
                ('media_type', models.CharField(choices=[('PHOTO', 'Photo'), ('DOCUMENT', 'Document'), ('CERTIFICATE', 'Certificate'), ('OTHER', 'Other')], default='PHOTO', max_length=20)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('captured_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FAMILY_ONLY', 'Family Only'), ('PRIVATE', 'Private')], default='FAMILY_ONLY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='families.family')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_items', to='members.person')),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
